# Generated by Django 4.1.2 on 2022-11-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('pkvalue', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=25, unique=True)),
                ('PW', models.CharField(max_length=25, unique=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pkvalue', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('contents', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, upload_to='bbs/fiels/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.category')),
                ('user_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('pkvalue', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs.post')),
                ('user_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs.user')),
            ],
        ),
    ]
