# Generated by Django 4.1.2 on 2022-11-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.user'),
        ),
    ]
