# Generated by Django 4.1.2 on 2022-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_alter_comment_post_alter_comment_user_pk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_pk',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_pk',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
