# Generated by Django 4.1.2 on 2022-11-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_rename_contents_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
